regex_patterns:
  object:
    - '\\D'  # Remove non-digit characters for object columns
  float64:
    - '[^\\d.]'  # Remove non-digit characters except dot for float columns
  int64:
    - '\\D'  # Remove non-digit characters for int columns
  datetime64[ns]:
    - '.*'  # Replace all content in datetime columns
  bool:
    - 'False'  # Remove 'False' for boolean columns

scan_patterns:
  #- '\d+'         # Regex to find any digit
  #- "[a-z]"       # Regex to find any lowercase letter
  #- "(\\d{3}|\\(\\d{3}\\))(:?\\s+|-|\\.)?(\\d{3})(:?\\s+|-|\\.)?(\\d{4})"
  - "(\\d{3}|\\(\\d{3}\\))(:?\\s+|-|\\.)?(\\d{3})(:?\\s+|-|\\.)?(\\d{4})"